[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
ignore = ["F401"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["B011"]

[tool.pytest.ini_options]
addopts = "--cov --cov-branch --no-cov-on-fail -ra --tb short -p pytester"
testpaths = ["tests"]


[tool.coverage.run]
branch = true
source = ["fancycompleter", "tests"]

[tool.coverage.paths]
source = ["tests", "*/site-packages"]


[tool.mypy]
# Error output
show_column_numbers = true
show_error_codes = true
show_error_context = true
show_traceback = true
pretty = true
check_untyped_defs = true
# Warnings
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
strict_equality = true
no_implicit_optional = true
warn_unused_configs = true
files = ["fancycompleter", "tests"]
