name: Publish package to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: |
            setup.py
      - name: Install nox
        run: |
          uv pip install nox
          nox --version
      - name: Build
        run: nox -s build

      # disabled until we get permissions for PyPI
      # - name: Upload package
      #   if: github.event_name == 'release'
      #   uses: pypa/gh-action-pypi-publish@release/v1

